### ISSUE TITLE
ModuleNotFoundError: No module named 'efficientnet_pytorch'

### ISSUE THREAD

**Issue by ghost** [chenjun2hao/GIOU_EAST#1]
@SakuraRiven @chenjun2hao 
When I run:
```
CUDA_VISIBLE_DEVICES=1 python detect.py
```
I get error:
```
(final) home@home-desktop:~/p3/GIOU_EAST$ CUDA_VISIBLE_DEVICES=1 python detect.py
Traceback (most recent call last):
  File "detect.py", line 5, in <module>
    from efficient_model import EAST
  File "/home/home/p3/GIOU_EAST/efficient_model.py", line 1, in <module>
    from efficientnet_pytorch import EfficientNet
ModuleNotFoundError: No module named 'efficientnet_pytorch'
```

**Comment by chenjun2hao** [comment]
@deepseek ，You can comment that code because I didn't use it later, other you can refer this [link](https://github.com/lukemelas/EfficientNet-PyTorch) for install efficientnet_pytorch

**Comment by deepseek** [comment]
@chenjun2hao if you don't use it, why don't you hash it out from the repo code?
